name: CI-CD-Pipeline
env:
  EB_PACKAGE_S3_BUCKET_NAME : "lab4-install-packages"
  EB_APPLICATION_NAME       : "MyLab4"
  EB_ENVIROMENT_NAME        : "MyLab4-env"
  DEPLOY_PACKAGE_NAME       : "lab4_app_${{ github.sha }}.zip"
  AWS_REGION_NAME           : "us-east-2"

on:
  push:
    branches: 
      - main 
    
jobs:
  ci_part:
      runs-on: ubuntu-latest
      
      steps:
      - name: Git clone repo
        uses: actions/checkout@v1
            
      - name: Create ZIP deployment package
        run : zip -r ${{ env.DEPLOY_PACKAGE_NAME }}  ./ -x *.git*       
      
      - name: Configure AWS Credentials
        uses: aws-action/configure-aws-credentials@v1
        with:
          aws-access-key-id : ${{ secrets.MY_AWS_ACCESS_KEY }}
          aws-access-key-key: ${{ secrets.MY_AWS_SECRET_KEY }}
          aws-region        : ${{ env.AWS_REGION_NAME }}

      - name: Copy Deployment package to S3 bucket
        run : aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME }}/
      - name: finish
        run : echo "SUCCESSFULLY!!!"
      
      
    


